version: "3.1"
services:
  infsectest_bot:
    container_name: infsectest_bot

    build:
        context: .

    command: python main.py
    restart: always
    volumes:
        - .:/src
    env_file:
        - '.env'
    networks: 
        - infsectest_botnet

networks: 
    infsectest_botnet:
        driver: bridge



         

        